### ISSUE TITLE
`module_dir` is undefined and if `warn_symlink` is ever reached causing modulebuilder to crash

### ISSUE THREAD

**Issue by mmarod** [puppetlabs/puppet-modulebuilder#34]
## Describe the Bug
`module_dir` is undefined and if `warn_symlink` is ever reached, modulebuilder crashes

https://github.com/puppetlabs/puppet-modulebuilder/blob/v0.2.1/lib/puppet/modulebuilder/builder.rb#L137

## Expected Behavior
A warning is sent without crashing

## Steps to Reproduce
```
$ ln -s Rakefile Rakefilelink
$ pdk bundle exec rake "litmus:install_modules_from_directory"
pdk (INFO): Using Ruby 2.5.8
pdk (INFO): Using Puppet 6.18.0
Building all modules in "./spec/fixtures/modules"
Building './spec/fixtures/modules/xxx' into 'xxx/pkg'
Building './spec/fixtures/modules/xxx' into 'xxx/pkg'
Building './spec/fixtures/modules/xxx' into 'xxx/pkg'
Building './spec/fixtures/modules/xxx' into 'xxx/pkg'
Building './spec/fixtures/modules/xxx' into 'xxx/pkg'
rake aborted!
NameError: undefined local variable or method `module_dir' for #<Puppet::Modulebuilder::Builder:0x00007fe59b2584a0>
Did you mean?  module_target_dir
/opt/puppetlabs/pdk/share/cache/ruby/2.5.0/gems/puppet-modulebuilder-0.2.1/lib/puppet/modulebuilder/builder.rb:137:in `warn_symlink'
/opt/puppetlabs/pdk/share/cache/ruby/2.5.0/gems/puppet-modulebuilder-0.2.1/lib/puppet/modulebuilder/builder.rb:105:in `stage_path'
/opt/puppetlabs/pdk/share/cache/ruby/2.5.0/gems/puppet-modulebuilder-0.2.1/lib/puppet/modulebuilder/builder.rb:83:in `block in stage_module_in_build_dir'
/opt/puppetlabs/pdk/share/cache/ruby/2.5.0/gems/puppet-modulebuilder-0.2.1/lib/puppet/modulebuilder/builder.rb:75:in `stage_module_in_build_dir'
/opt/puppetlabs/pdk/share/cache/ruby/2.5.0/gems/puppet-modulebuilder-0.2.1/lib/puppet/modulebuilder/builder.rb:47:in `build'
/Users/xxx/.pdk/cache/ruby/2.5.0/gems/puppet_litmus-0.22.0/lib/puppet_litmus/rake_helper.rb:263:in `build_module'
/Users/xxx/.pdk/cache/ruby/2.5.0/gems/puppet_litmus-0.22.0/lib/puppet_litmus/rake_helper.rb:282:in `block in build_modules_in_dir'
/Users/xxx/.pdk/cache/ruby/2.5.0/gems/puppet_litmus-0.22.0/lib/puppet_litmus/rake_helper.rb:276:in `map'
/Users/xxx/.pdk/cache/ruby/2.5.0/gems/puppet_litmus-0.22.0/lib/puppet_litmus/rake_helper.rb:276:in `build_modules_in_dir'
/Users/xxx/.pdk/cache/ruby/2.5.0/gems/puppet_litmus-0.22.0/lib/puppet_litmus/rake_tasks.rb:235:in `block (2 levels) in <top (required)>'
/Users/xx/.pdk/cache/ruby/2.5.0/gems/honeycomb-beeline-2.4.0/lib/honeycomb/integrations/rake.rb:21:in `block in execute'
/Users/xxx/.pdk/cache/ruby/2.5.0/gems/honeycomb-beeline-2.4.0/lib/honeycomb/client.rb:70:in `start_span'
/Users/xxx/.pdk/cache/ruby/2.5.0/gems/honeycomb-beeline-2.4.0/lib/honeycomb/integrations/rake.rb:16:in `execute'
/opt/puppetlabs/pdk/private/ruby/2.5.8/bin/bundle:23:in `load'
/opt/puppetlabs/pdk/private/ruby/2.5.8/bin/bundle:23:in `<main>'
Tasks: TOP => litmus:install_modules_from_directory
(See full trace by running task with --trace)
```

Removing `Rakefilelink` and running the command again will result in a successful rake

## Environment
 - Version [e.g. 1.27.0]
 - Platform [e.g. Ubuntu 18.04]

**Comment by ekohl** [comment]
It does look like this never worked. From reading the code I think that should be `source` instead of `module_dir`. Could you come up with a patch and tests?
